name: CI
on:
  push:
  schedule:
    - cron:  '0 4 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.108.0"
          extended: true

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo -F --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: HelSec/helsec.github.io 
          publish_dir: ./public
          #   keep_files: true
          user_name: HelSec-bot
          user_email: contact@helsec.fi
          publish_branch: main
        #   cname: example.com
