name: check_events
on:
  workflow_dispatch:

jobs:
  check-events:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Execute python
        run: |
          python get_events.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update events!"
          commit_user_name: HelSec-bot
          commit_user_email: contact@helsec.fi
          commit_author: HelSec-Bot <contact@helsec.fi>
